Book_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

from django.contrib import admin
from django.urls import path, include

# import index.html;



urlpatterns = [
    path('', include('core.urls')), 
    path('items/', include('items.urls')), 
    path('dashboard', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static() are always outside of the urlpatterns!nts

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_user, name='logout_user'),
    path('contact/',views.contact, name='contact'),
    path('signup/' , views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html' ,authentication_form=LoginForm), name="login"),
]



# 1:12:45

dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'


urlpatterns = [
    path('', views.browser, name="browser"),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name="detail")
]


# 50:04

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

items/models.py
from django.db import models
from django.contrib.auth.models import User


# pass : i٢z0zYij']
# Create your models here.
class Category(models.Model):
    
    # NOTE!!!!! please keep in mind that you need 
    # to do this every time you do somethig here..
    # after you Done!
    # use makemigrations afer then use migrate!
    # lasty register that at admin.py!
    name = models.CharField(max_length=255)
    
    # change the objects 's'
    class Meta:
        ordering  = ('name', )
        verbose_name_plural = 'Categoreis'
        
    def __str__(self):
        return self.name

# Item object in the DataBase Admin!!!
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    descripion = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_image', blank='True', null=True)    
    sold_out = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'username',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
     
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
     
     
    


class SignupForm(UserCreationForm):
    model = User
    fields = ('nickname','username', 'email', 'password1', 'password2')
    
    # nickname = forms.CharField(widget=forms.TextInput(attrs={
    #     'placeholder': 'nickname',
    #     'class': 'w-full py-2 px-3 rounded-l'
    # }))
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'username',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'email address',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'reapeat password',
        'class': 'w-full py-2 px-3 rounded-l'
    }))
    
    
# 1:08:05

core/views.py
from django.shortcuts import render, redirect
from items.models import Category, Item
from django.contrib import messages
from django.contrib.auth import logout
from . import views
from .forms import SignupForm

# Create your views here.
def index(request):
    # this condition will filter the 8 items only!
    # items = Item.objects.filter(sold_out=False)[0:8]
    items = Item.objects.all()
    categories = Category.objects.all()
    
    return render(request, 'core/index.html',{
        'categories': categories,
        'items':items,
    })
def contact(request):
    return render (request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })
    
def logout_user(request):
    logout(request)
    messages.success(request, ("You were logged Out!"))
    return redirect('core:index')

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from items.models import Item
# Create your views here.

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)
    
    return render(request, 'dashboard/index.html', {
        'items' : items,
    })

items/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .form import NewItemForm
from .models import Item, Category


def browser(request):
    category_id = request.GET.get('category', 0)
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    items = Item.objects.filter(sold_out=False)
    
    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains= query) | Q(descripion__icontains=query))    
    
    return render(request, 'items/browser.html', {
        'items': items,
        'query': query,
        'categories': categories,
        "category_id": int(category_id)
        
        
    })
# Create your views here.

def detail(request, pk):
    items = get_object_or_404(Item, pk=pk)
    releted_items = Item.objects.filter(category =items.category, sold_out=False).exclude(pk=pk) [0:3]
    
    
    return render(request, 'items/detail.html', {
        'items': items,
        'releted_items':releted_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            
            return redirect('items:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'items/form.html', {
        'form': form,
        'title': 'New item',
        })    
 

core/templates/core/base.html
<!doctype html>

    <html>
        <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">

                <!-- <link rel="stylesheet" type="text/css" href=""> -->
                <script src="https://cdn.tailwindcss.com"></script>

                <title> {% block title %}{% endblock %} MarsBook's</title>
        </head>

        <body class="bg-white dark:bg-gray-800">

            <nav class=" navbar navbar-expand-lg bd-navbar bg-light sticky-top py-6 px-6 flex justify-between items-center border-b brder-blue-200">
                <a href="{% url 'core:index'%}" class="text-gray-900 dark:text-white text-xl font-semibold"> 
                    MarsBook</a>
            
            
                <div class="space-x-6 d-md-inline-flex">
                    <a href="{% url 'items:new' %}" class="text-gray-900 dark:text-white text-lg font-semibold hover:text-blue-500"> 
                        New Items</a>
                    <a href="{% url 'items:browser'%}" class="text-gray-900 dark:text-white text-lg font-semibold hover:text-blue-500">
                         Browse</a>
                        
                    {% if request.user.is_authenticated %}
                   <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-gray-900 dark:text-white text-lg front-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"> 
                       DashBoard</a>
                    <a href="{% url 'core:logout_user' %}" class="px-6 py-3 text-gray-900 dark:text-white text-lg front-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                        logout</a>

                    {% else  %}
                     <div class="text-justify mt-0 px-2 py-1 text-gray-900 dark:text-white text-lg front-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">
                    <a href="{% url 'core:signup' %}">
                         Signin/</a>
                    <a href="{% url 'core:login' %}" > 
                        Login</a>
                        <div>
                    {% endif %}
            </div>
            </nav>

                <div class="px-6 py-6">
                   {% block content %}

                   {% endblock  %}

                </div>

            <footer class="py-6 px-6 flex justify-between bg-gray-800">
                <div class="w-2/3 pr-10">
                        <h3 class="mb-5 font-semibold text-gray-400">
                            About </h3>
                        
                        <p class="text-lg text-gray-500"> lorem ipsum bla bla.lorem ipsum bla bla. lorem ipsum bla bla.
                            lorem ipsum bla bla.</p> 
                </div>
                
                <div class="w-1/3">
                    <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                    <ul class="space-y-2">
                        <li> <a href="#" class="tex-lg text-teal-500 hover:text-teal-700">AboutUs </a> </li>

                        <li> <a href="{% url 'core:contact' %}" class="tex-lg text-teal-500 hover:text-teal-700">Contact </a> </li>
                    </ul>
                </div>
            
            </footer>

        </body>

    </html>
{% comment %} 
21:52 {% endcomment %}

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title%}
    Contact
{% endblock %}

{% block content %}
    <h1>Contact page?</h1>
{% endblock%}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title%}
    Welcome  |
{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-6 bg-gray-500 rounded-xl bg-secondary">
            <h2 class="mb-12 bg-orange-100 text-2xl text-center">
                Newest Books
            </h2>

            <div class="grid grid-cols-4 gap-3 ">
                    {% for items in items %}
                    <div>
                        <a href="{% url 'items:detail' items.id %}">
                            <div>
                                <img src="{{ items.image.url }}" class="rounded-t-xl" >
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ items.name }} </h2>
                                <p class="text-gray-500"> Price: ₱{{ items.price}}</p>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
            </div>
    </div>

    <div class="mt-6 py-12 bg-gray-100 rounded-xl bg-success">
        <h2 class="mb-12 text=2xl text-center">
            Genres
        </h2>

        <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                <div>
                    <a href="#">

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }} </h2>
                            <p class="text-gray-500"> {{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title%} Sign up {% endblock %}

{% block content %}
    <div class="w-1/2 mx-auto p-6 bg-blue-100 rounded-xl">
            <h1 class="mb-6 text-3xl">
                    Log in
            </h1>


            <form method="post" action=".">
                {% csrf_token %}
         

                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Username:
                    </label><br>
                            {{ form.username }}
                </div>


                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Password:
                    </label><br>
                            {{ form.password }}
                </div>

                {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                            {% endfor %}

                                   
                      {{form.non_field_errors}}
                </div>
                {% endif %}

                <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
                    Submit

                </button>
            </form>

    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title%} Sign up {% endblock %}

{% block content %}
    <div class="w-1/2 mx-auto p-6 bg-blue-100 rounded-xl">
            <h1 class="mb-6 text-3xl">
                    Sign up
            </h1>


            <form method="post" action=".">
                {% csrf_token %}
                

                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Nickname:
                    </label><br>
                            {{ form.nickname }}
                </div>


                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Username:
                    </label><br>
                            {{ form.username }}
                </div>

                <div class="mb-3">
                    <label class="inline-block mb-2">
                       Email:
                    </label><br>
                   
                    {{ form.email }}
                </div>

                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Password:
                    </label><br>
                            {{ form.password1 }}
                </div>


                <div class="mb-3">
                    <label class="inline-block mb-2">
                        Repeat password:
                    </label><br>
                            {{ form.password2 }}
                </div>  

                {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                            {% endfor %}

                                   
                      {{form.non_field_errors}}
                </div>
                {% endif %}

                <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
                    Submit

                </button>
            </form>

    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "core/base.html" %}

{% block title%}
    DashBoard
{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">
                My Books
            </h2>

            <div class="grid grid-cols-4 gap-3">
                    {% for items in items %}
                    <div>
                        <a href="{% url 'items:detail' items.id %}">
                            <div>
                                <img src="{{ items.image.url }}" class="rounded-t-xl">
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ items.title }} </h2>
                                <p class="text-gray-500"> Price: {{ items.price}}</p>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
            </div>
    </div>


    </div>
{% endblock %}

items/templates/items/browser.html
{% extends 'core/base.html' %}

{% block title %}
    Items
{% endblock%}

{% block content%}

    <div class="pb-6 grid grid-cols-2 gap-4 bg-blue-100">

        <div class="cols-span-1">
            <form method="get" action="{% url 'items:browser'%}">

                <input name="query" class='w-full py-4 px-6 border rounded-xl' type="text" value="{{ query }}" placeholder="Find your Book here...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">
                    Search
                </button>
            </input>

            </form>
            
            <hr class="my-6">

            <p class="font-semibold"> 
                Genres
            </p>
            <ul> 
                {% for category in categories %}
                <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-orange-200"{% endif%}">
                    <a href="{% url 'items:browser'%}?query={{ query }}&category={{ category.id}}">
                        {{ category.name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="cols-span-5 mr-10">

            <div class="grid grid-cols-3 gap-3">
                {% for items in items %}
                <div>
                    <a href="{% url 'items:detail' items.id %}">
                        <div>
                            <img src="{{ items.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ items.name }} </h2>
                            <p class="text-gray-500"> Price: ₱{{ items.price}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
        </div>
    </div>

{% endblock%}

items/templates/items/detail.html
{% extends 'core/base.html' %}

{% block title%} {{ items.name }} {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class=" cols-pan-3">
            <img src="{{ items.image.url }}" class="rounded-xl"> 

        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">
                    {{items.name}}
            </h1>
            <p class="text-gray-500">
                <strong>
                        Price:{{items.price}}
                </strong>
            </p>
            <p class="text-gray-500">
                <strong>
                        Seller:{{items.created_by.username}}
                </strong>
            </p><br>
            
            {% if items.descripion %}
            <p class="text-gray-100">
                    <strong class="text-gray-500">Description:<br>
                        <br>{{ items.descripion }}
                    </strong>
            </p>
            {% endif %}

            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Me

            </a>

            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-red-700">Buy

            </a>

        </div>
    </div>

    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">
            Related Items
        </h2>

        <div class="grid grid-cols-3 gap-3">
                {% for items in releted_items %}
                <div>
                    <a href="{% url 'items:detail' items.id %}">
                        <div>
                            <img src="{{ items.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ items.title }} </h2>
                            <p class="text-gray-500"> Price: {{ items.price}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
        </div>
</div>

{% endblock %}

items/templates/items/form.html
{% extends 'core/base.html' %}

{% block title %}
         {{title}}
{% endblock%}

{% block content %}
    <h1 class="mb-6 text-3xl">
            {{ title }}
    </h1>
    <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            <div class="space-y-4">
                {{ form.as_p }}
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                        {% endfor %}

                               
                  {{form.non_field_errors}}
            </div>
            {% endif %}

            <button class="mt-10 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
                Submit

            </button>
    </form>

{% endblock %}